### ISSUE TITLE
Original 2.11 tarball is no longer accessible at original URL, update to 2.13

### ISSUE THREAD

**Issue by nkadel-skyhook** [johnbellone/jmeter-cookbook#3]
The old URL and checksums and version need to be updated to 2.13, or the download pointed to the archive repository to avoid getting broken again.

**Comment by johnbellone** [comment]
I'll verify this. I'm going to cleanup the cookbook a bit and then release revision as 1.0.

**Comment by nkadel-skyhook** [comment]
Fabulous, thank you. Similar things happened with the old nagios and tomcat cookbooks, back in the day, I'd actually like to see this one in EPEL, but it will take longer than I have right now to do something like that.

**Comment by johnbellone** [comment]
You can use the master branch for now. I'll be releasing this in upcoming days on Supermarket.
